import { fontFamily, fontWeight, rounded, color } from "./";

export const defaultTheme = {
  color,
  fontFamily,
  fontWeight,
  font: {
    displayLarge: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    displayMedium: {
      fontSize: 37,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    displaySmall: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    headlineLarge: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    headlineMedium: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    headlineSmall: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    titleLarge: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    titleMedium: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    titleSmall: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    labelLarge: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    labelMedium: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    labelSmall: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    bodyLarge: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
    bodyMedium: {
      fontSize: 27,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 10,
      letterSpacing: 5,
    },
    bodySmall: {
      fontSize: 57,
      fontFamily: fontFamily.brand,
      fontWeight: fontWeight.bold,
      lineHeight: 23,
      letterSpacing: 5,
    },
  },
  rounded,
};
