import { fontFamily, fontWeight, rounded, color, Theme } from "./";

export const defaultTheme: Theme = {
  color,
  fontFamily,
  fontWeight,
  font: {
    displayLarge: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    displayMedium: {
      fontSize: "37px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    displaySmall: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    headlineLarge: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    headlineMedium: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    headlineSmall: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    titleLarge: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    titleMedium: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    titleSmall: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    labelLarge: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    labelMedium: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    labelSmall: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    bodyLarge: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
    bodyMedium: {
      fontSize: "27",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "10px",
      letterSpacing: "5px",
    },
    bodySmall: {
      fontSize: "57px",
      fontFamily: (t: Theme) => t.fontFamily.brand,
      fontWeight: (t: Theme) => t.fontWeight.bold,
      lineHeight: "23px",
      letterSpacing: "",
    },
  },
  spacing: 1,
  rounded,
};
